// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGmQeck1-nlgOWrTU6NHq5_h2LwDajG-0',
    appId: '1:276853219035:web:7b546f5ee0a9133923b6fe',
    messagingSenderId: '276853219035',
    projectId: 'rizwan-trader',
    authDomain: 'rizwan-trader.firebaseapp.com',
    databaseURL: 'https://rizwan-trader-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rizwan-trader.appspot.com',
    measurementId: 'G-MXG18EHEL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5mBhzBNjnsHaIkQnqVdyliSVQZLep1qY',
    appId: '1:276853219035:android:1ee82183f4c0262023b6fe',
    messagingSenderId: '276853219035',
    projectId: 'rizwan-trader',
    databaseURL: 'https://rizwan-trader-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rizwan-trader.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn8NhwGh5Qv4z69nYnfkTzte1IytAfuDE',
    appId: '1:276853219035:ios:3d29716c4823422f23b6fe',
    messagingSenderId: '276853219035',
    projectId: 'rizwan-trader',
    databaseURL: 'https://rizwan-trader-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rizwan-trader.appspot.com',
    androidClientId: '276853219035-bh04oav95ar895sr11q6pg2f6eom9et9.apps.googleusercontent.com',
    iosClientId: '276853219035-ohnoq4qk4v0d47etfb0qc57lmqkflaj4.apps.googleusercontent.com',
    iosBundleId: 'com.example.rizwanTrader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn8NhwGh5Qv4z69nYnfkTzte1IytAfuDE',
    appId: '1:276853219035:ios:3d29716c4823422f23b6fe',
    messagingSenderId: '276853219035',
    projectId: 'rizwan-trader',
    databaseURL: 'https://rizwan-trader-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rizwan-trader.appspot.com',
    androidClientId: '276853219035-bh04oav95ar895sr11q6pg2f6eom9et9.apps.googleusercontent.com',
    iosClientId: '276853219035-ohnoq4qk4v0d47etfb0qc57lmqkflaj4.apps.googleusercontent.com',
    iosBundleId: 'com.example.rizwanTrader',
  );
}
